
SELECT * FROM
(select t1.*,row_number() over(partition by T1.SFC order by T1.ID desc) as RN,T6.DATA_ATTR
from Z_SFC_RECEIVED t1
join sfc t2 on t2.SFC=t1.SFC AND T1.SITE=2210
join CUSTOM_FIELDS t3 on t3.HANDLE=t2.ITEM_BO and t3.ATTRIBUTE='PROJECT_NAME'
join CUSTOM_FIELDS t4 on t4.HANDLE=t2.ITEM_BO and t4.ATTRIBUTE='ITEM_NAME'
JOIN SFC_DATA T5 ON T5.SFC_BO=T2.HANDLE AND T5.DATA_FIELD='MODEL'
JOIN SFC_DATA T6 ON T6.SFC_BO=T2.HANDLE AND T6.DATA_FIELD='MARK_NO'
JOIN SFC_DATA T7 ON T7.SFC_BO=T2.HANDLE AND T7.DATA_FIELD='HOLE'
--where T1.SFC='200122N79R'
where t3.VALUE='125064A01'
AND T4.VALUE in ('P2')
-- AND T5.DATA_ATTR in ('N1')
--AND T6.DATA_ATTR in ('Z26-3')
-- AND T7.DATA_ATTR in ('5#')
) Z
WHERE Z.RN=1 AND Z.TYPE IS NULL
------------------------
select * from CUSTOM_FIELDS where HANDLE ='ItemBO:5060,1200041984,1' ;




		

