

--查询镀膜入库数量
SELECT C.PROJECT_NAME '项目名',C.MODEL_ID,C.PART_NAME, SUM(A.QTY) '数量',SUBSTRING(CONVERT(varchar,B.CREATE_DATE_TIME,20),1,7) '日期',A.OPERATION
	FROM PRODUCTION_LOG A,Z_LensID_SFC B,Z_LensCPSNInfo C
	WHERE A.SFC = B.SFC
	AND B.LENS_ID=C.ID
	AND C.PROJECT_NAME IN ('486030A01','165227')
	AND B.CREATE_DATE_TIME BETWEEN '2021-01-01 00:00:01.000' AND '2021-06-01 00:00:01.000'
	AND A.OPERATION = 'ZJCJXX'
	GROUP BY C.PROJECT_NAME,C.MODEL_ID,C.PART_NAME,SUBSTRING(CONVERT(varchar,B.CREATE_DATE_TIME,20),1,7),A.OPERATION
	ORDER BY C.PROJECT_NAME,C.MODEL_ID,C.PART_NAME,SUBSTRING(CONVERT(varchar,B.CREATE_DATE_TIME,20),1,7) DESC
	
	
	
--写法2
SELECT distinct C.PROJECT_NAME '项目名',
	C.MODEL_ID,
	C.PART_NAME, 
	SUM(A.QTY) over (partition by C.MODEL_ID,C.PART_NAME,SUBSTRING(CONVERT(varchar,B.CREATE_DATE_TIME,20),1,7)) '数量',
	SUBSTRING(CONVERT(varchar,B.CREATE_DATE_TIME,20),1,7) '日期'
	FROM PRODUCTION_LOG A,Z_LensID_SFC B,Z_LensCPSNInfo C
		WHERE A.SFC = B.SFC
		AND B.LENS_ID=C.ID
		AND C.PROJECT_NAME = '165227'--('486030A01','165227')
		AND B.CREATE_DATE_TIME > '2021-01-01 00:00:01.000'
		AND A.OPERATION = 'ZSJSXX'
		ORDER BY C.MODEL_ID,C.PART_NAME,SUBSTRING(CONVERT(varchar,B.CREATE_DATE_TIME,20),1,7) DESC